import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./modale.module.css";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className={styles.modale}>
          <header className={styles.header}>
            <h1 className={styles.title}>6: The boardgame</h1>
          </header>
          <main className={styles.content}>{children}</main>
        </section>
      </body>
    </html>
  );
}
